# Generated by Django 3.2.3 on 2021-08-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=100)),
                ('employee_salary', models.FloatField()),
                ('employee_age', models.IntegerField()),
                ('employee_email_id', models.EmailField(max_length=254)),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_gender', models.CharField(max_length=100)),
                ('employee_designation', models.CharField(choices=[('Java Developer', 'JAVA DEVELOPER'), ('Software Tester', 'SOFTWARE TESTER'), ('Python Developer', 'PYTHON DEVELOPER'), ('Manager', 'MANAGER')], default='Select Designation', max_length=100)),
            ],
        ),
    ]
